# Generated by Django 4.2.4 on 2023-08-09 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='question',
            field=models.TextField(default='기본 텍스트', max_length=300),
            preserve_default=False,
        ),
    ]
