# Generated by Django 4.2.4 on 2023-08-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_member_star_score_alter_member_total_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='star_score',
            new_name='chat_count',
        ),
        migrations.AddField(
            model_name='member',
            name='profile',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='review_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
