# Generated by Django 4.2.4 on 2023-08-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_member_foreign_univ_alter_member_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='subject',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
