# Generated by Django 4.2.4 on 2023-08-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_member_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='subject',
        ),
        migrations.AddField(
            model_name='member',
            name='tag1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='tag2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
