# Generated by Django 4.2.4 on 2023-08-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_member_subject_member_tag1_member_tag2'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='tag3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
